In [1]:
import numpy as np
import pandas as pd

In [2]:
X_train = pd.read_csv('../Feature Selection/X_train_flats_test.csv',index_col=0,)
X_test = pd.read_csv('../Feature Selection/X_test_flats_test.csv',index_col=0)
y_train = pd.read_csv('../Feature Selection/y_train_flats.csv',index_col=0)
y_test = pd.read_csv('../Feature Selection/y_test_flats.csv',index_col=0)

In [9]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error

In [26]:
ridge = Ridge(alpha=94)
ridge.fit(X_train,y_train)
y_pred = ridge.predict(X_test)
# y_pred = np.expm1(y_pred)
mean_absolute_error(y_test,y_pred)

0.8398823306504554

In [27]:
ridge.coef_

array([ 2.26670274,  2.15914715,  0.80806764,  1.0507426 , -0.4336663 ,
        0.04528005,  0.0048159 , -0.02395417,  0.01069174, -0.0254029 ,
        0.10411626])

In [28]:
X_train.columns

Index(['Main Location', 'Building', 'Area(Marla)', 'Bath(s)', 'Bedroom(s)',
       'Servant Quarters', 'Kitchens', 'Parking Spaces', 'Property era',
       'Floor Level', 'Elevator Capacity'],
      dtype='str')

In [30]:
pd.DataFrame(index=X_train.columns,columns=['Coeffs'],data=ridge.coef_)

                     Coeffs
Main Location      2.266703
Building           2.159147
Area(Marla)        0.808068
Bath(s)            1.050743
Bedroom(s)        -0.433666
Servant Quarters   0.045280
Kitchens           0.004816
Parking Spaces    -0.023954
Property era       0.010692
Floor Level       -0.025403
Elevator Capacity  0.104116

In [31]:
X_train

,Main Location,Building,Area(Marla),Bath(s),Bedroom(s),Servant Quarters,Kitchens,Parking Spaces,Property era,Floor Level,Elevator Capacity
6148,0.835680,0.835680,0.693147,1.0,1.0,1.0,1.0,1.0,3,2,1
4031,0.682126,0.688180,1.098612,1.0,1.0,0.0,1.0,1.0,4,2,1
1222,0.788549,0.800230,1.609438,3.0,3.0,1.0,1.0,1.0,3,2,1
1783,0.756197,0.800029,1.945910,2.0,2.0,1.0,1.0,1.0,3,2,3
1550,0.746192,0.746192,1.386294,2.0,2.0,1.0,1.0,1.0,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...
4366,1.020540,1.033151,1.386294,1.0,1.0,1.0,1.0,4.0,5,3,2
4931,1.113525,1.113525,1.945910,2.0,3.0,1.0,1.0,1.0,3,2,1
3332,0.986039,0.837520,1.098612,1.0,1.0,0.0,1.0,1.0,3,1,2
5650,0.763765,0.763765,1.098612,1.0,1.0,1.0,2.0,4.0,3,1,2
4348,0.756197,0.800029,0.693147,1.0,1.0,1.0,1.0,1.0,3,1,1